### ISSUE TITLE
AttributeError: module 'vyper' has no attribute 'set_default'

### ISSUE THREAD

**Issue by MareoRaft** [alexferl/vyper#40]
Maybe I'm doing something wrong, but I did the reasonable thing and tried out the first example in the README.

requirements.txt:
```
vyper-config==1.0.0
```

python file:
```
import vyper as v
v.set_default('ContentDir', 'content')
```

and I obtained the error `AttributeError: module 'vyper' has no attribute 'set_default'`.

Any idea as to how to fix this error?  Also, perhaps a **Getting Started** section or a tutorial would be helpful for newcomers.

**Comment by jjmerri** [comment]
You might be running into the same problem as me (which I havent solved). `vyper` is a different module. This module is `vyper-config` but I cant figure out how to import it.

**Comment by MareoRaft** [comment]
@jjmerri Thanks for the comment.  Glad to know I'm not the only one with this issue.

The name of a module in PyPI and the name of a module when importing can be different.  This module is called `vyper-config` in [PyPI](https://pypi.org/project/vyper-config/) but it is imported with `import vyper`.  To the best of my knowledge it is the correct module.

You can run `pip list | grep vyper` in the terminal to see if you have any other modules with "vyper" in their name installed.  You can uninstall the other ones in order to ensure that `import vyper` is not importing one of the other ones instead of this one.

**Comment by MareoRaft** [comment]
@alexferl Perhaps you took a cursory glance at my comment and thought it was a resolution.  The issue of receiving `AttributeError: module 'vyper' has no attribute 'set_default'` still has not been resolved.

**Comment by alexferl** [comment]
@MareoRaft indeed, I did. I just noticed your import is what's wrong. It should be:
```
from vyper import v
v.set_default('ContentDir', 'content')
```
Sorry about that, my brain must've [rearranged it](https://www.mrc-cbu.cam.ac.uk/people/matt.davis/cmabridge/) when I first read it.
